import math
print("dada uma matriz A3x3")
print("[X1,X2,X3]")
print ("[X4,X5,X6]")
print ("[X7,X8,X9]")
print("fonerca todos os valores de x, começando de X1, X2,...,X9")
X1=float(input())
X2=float(input())
X3=float(input())
X4=float(input())
X5=float(input())
X6=float(input())
X7=float(input())
X8=float(input())
X9=float(input())
print("[",X1,X2,X3,"]")
print("[",X4,X5,X6,"]")
print("[",X7,X8,X9,"]")
D=X1*((X5*X9)-(X6*X8)) - X4*((X2*X9)-(X3*X8)) + X7*((X2*X6-X3-X5))
print("seu determinante é",D)